name: Deploy Backend to Namecheap

on:
  push:
    paths:
      - 'mysource_backend/**'
      - '.github/workflows/backend-deploy.yml'
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: npm ci
        working-directory: ./mysource_backend

      - name: Create .env file for backend
        run: echo "${{ secrets.ENV_FILE_BACKEND }}" > .env
        working-directory: ./mysource_backend

      - name: Debug environment
        run: |
          echo "DATABASE_URL is $DATABASE_URL"
          cat .env
          env | grep DATABASE_URL
        working-directory: ./mysource_backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run Prisma migrations
        run: |
          npm install dotenv --save-dev
          node -r dotenv/config node_modules/.bin/prisma migrate deploy --schema=prisma/schema.prisma
        working-directory: ./mysource_backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Deploy backend via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./mysource_backend/
          server-dir: /home/mysofuhc/mysource.com.ng/
          exclude: |
            node_modules/**
            .env