name: Deploy Frontend to Namecheap

on:
  push:
    paths:
      - 'mysource_frontend/**'
      - '.github/workflows/frontend-deploy.yml'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install frontend deps
        run: npm install
        working-directory: ./mysource_frontend

      - name: Build React app
        run: |
          REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} \
          REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }} \
          REACT_APP_TELEGRAM_BOT_USERNAME=${{ secrets.REACT_APP_TELEGRAM_BOT_USERNAME }} \
          REACT_APP_TURNSTILE_SITE_KEY=${{ secrets.REACT_APP_TURNSTILE_SITE_KEY }} \
          REACT_APP_DISABLE_TURNSTILE=${{ secrets.REACT_APP_DISABLE_TURNSTILE }} \
          npm run build
        working-directory: ./mysource_frontend
      

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./mysource_frontend/build/
          server-dir: ./public_html/
